version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  bot:
    build: .
    command: ["python", "bot.py"]
    environment:
      - API_TOKEN=your_bot_token
    depends_on:
      - redis

  fetcher:
    build: .
    command: ["python", "currency_fetcher.py"]
    depends_on:
      - redis
